### ISSUE TITLE
Unable to use Neuron Cores while fine-tuning BERT on Trainium

### ISSUE THREAD

**Issue by DhruvaBansal00** [philschmid/aws-neuron-samples#3]
Hey!

I am trying to follow this guide: https://huggingface.co/docs/optimum-neuron/tutorials/fine_tune_bert and fine tune BERT on a trn1.2xlarge instance. I setup the datasets as mentioned in the blog and then ran the training script but the usage of neuron cores is still at 0%. The reason why this is relevant for me is because the expected training time for me is close to 5 hours.

<img width="1512" alt="Screenshot 2023-06-28 at 1 10 32 PM" src="https://github.com/philschmid/aws-neuron-samples/assets/26373935/8635af9e-9772-45fa-85e1-12cfb76a513c">

<img width="1512" alt="Screenshot 2023-06-28 at 1 09 34 PM" src="https://github.com/philschmid/aws-neuron-samples/assets/26373935/e38ebefb-ccd7-45e9-91f4-0e5c01c29cf2">

cc: @philschmid

**Comment by philschmid** [comment]
Thank you for reporting can. When did you create your environment? It seems that there is an error with the new AMI. Can you use the previous one?

**Comment by DhruvaBansal00** [comment]
I created the environment yesterday, using this AMI:  huggingface-neuron-2023-06-26T09-27-02.137Z-692efe1a-8d5c-4033-bcbc-5d99f2d4ae6a. I can try the previous one.

**Comment by DhruvaBansal00** [comment]
Trying huggingface-neuron-2023-04-20T11-02-28.279Z-692efe1a-8d5c-4033-bcbc-5d99f2d4ae6a

**Comment by DhruvaBansal00** [comment]
Ok that AMI works, thanks for your quick response!

I had to undo my PR to make it work on the previous AMI - https://github.com/philschmid/aws-neuron-samples/pull/2

I am trying to train a T5 model. Do you know if this AMI can be used to train a T5 model?

**Comment by philschmid** [comment]
Thank you! We are working on fixing that ASAP!
